# Generated by Django 2.2.9 on 2020-02-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0002_pagevisits'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PageVisits',
        ),
        migrations.AddField(
            model_name='categories',
            name='cat_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='list_views',
            field=models.IntegerField(default=0),
        ),
    ]
