# Generated by Django 2.2.9 on 2020-02-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0003_auto_20200201_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=20, unique=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='HomePageVisits',
        ),
    ]
